import { Product } from './types';

export const CURRENCY = "RWF"; 

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Ankara Print Maxi Dress',
    price: 45000,
    currency: CURRENCY,
    category: 'Fashion',
    image: 'https://picsum.photos/400/500?random=1',
    rating: 4.8,
    reviews: 124,
    isSponsored: true,
    isVerifiedSeller: true,
    sellerName: 'Mama Africa Styles',
    description: 'Authentic wax print dress, perfect for weddings and formal events. Hand-stitched details.',
    stock: 15,
  },
  {
    id: 'p2',
    name: 'Wireless Noise Cancelling Headphones',
    price: 120000,
    currency: CURRENCY,
    category: 'Electronics',
    image: 'https://picsum.photos/400/400?random=2',
    rating: 4.5,
    reviews: 89,
    isSponsored: true,
    isVerifiedSeller: true,
    sellerName: 'TechHub Kigali',
    description: 'Premium sound quality with 24-hour battery life. Comfortable over-ear design.',
    stock: 42,
  },
  {
    id: 'p3',
    name: 'Handwoven Raffia Basket',
    price: 15000,
    currency: CURRENCY,
    category: 'Home & Living',
    image: 'https://picsum.photos/400/400?random=3',
    rating: 4.9,
    reviews: 56,
    isVerifiedSeller: true,
    sellerName: 'Crafts of Rwanda',
    description: 'Durable and eco-friendly storage basket tailored by local artisans.',
    stock: 100,
  },
  {
    id: 'p4',
    name: 'Smart Fitness Watch Gen 4',
    price: 85000,
    currency: CURRENCY,
    category: 'Electronics',
    image: 'https://picsum.photos/400/400?random=4',
    rating: 4.2,
    reviews: 200,
    isSponsored: true,
    isVerifiedSeller: false,
    sellerName: 'Gadget World',
    description: 'Track your steps, heart rate, and sleep. Waterproof and durable.',
    stock: 8,
  },
  {
    id: 'p5',
    name: 'Organic Shea Butter (500g)',
    price: 8000,
    currency: CURRENCY,
    category: 'Beauty',
    image: 'https://picsum.photos/400/400?random=5',
    rating: 4.7,
    reviews: 310,
    isVerifiedSeller: true,
    sellerName: 'Natural Glow',
    description: 'Pure unrefined shea butter. Great for skin and hair.',
    stock: 200,
  },
  {
    id: 'p6',
    name: 'Leather Sandals (Unisex)',
    price: 30000,
    currency: CURRENCY,
    category: 'Fashion',
    image: 'https://picsum.photos/400/500?random=6',
    rating: 4.4,
    reviews: 45,
    isVerifiedSeller: true,
    sellerName: 'Kigali Leatherworks',
    description: 'Handcrafted genuine leather sandals. Durable rubber sole.',
    stock: 30,
  },
  {
    id: 'p7',
    name: 'Solar Power Bank 20000mAh',
    price: 55000,
    currency: CURRENCY,
    category: 'Electronics',
    image: 'https://picsum.photos/400/400?random=7',
    rating: 4.6,
    reviews: 150,
    isSponsored: true,
    isVerifiedSeller: true,
    sellerName: 'Green Energy Solutions',
    description: 'Charge your devices on the go with solar power. Includes flashlight.',
    stock: 55,
  },
  {
    id: 'p8',
    name: 'Beaded Necklace Set',
    price: 12000,
    currency: CURRENCY,
    category: 'Fashion',
    image: 'https://picsum.photos/400/400?random=8',
    rating: 4.8,
    reviews: 22,
    isVerifiedSeller: true,
    sellerName: 'Rwanda Arts',
    description: 'Traditional vibrant beadwork. Necklace and earring set.',
    stock: 12,
  },
];

export const SPONSORED_PRODUCTS = MOCK_PRODUCTS.filter(p => p.isSponsored);